name: 'Actualizacion del README.md'
description: 'Actualiza un README, en caso que no exista lo crea'
inputs:
  template:  # id of input
    description: 'Tipo de readme a crear'
    required: false
    default: 'modulo' 
    #possible values: modulo, practica, proyecto
  readme_path:
    description: 'Path of the readme file to update'
    default: "./README.md"
    required: false
runs:
  using: 'node12' #currently only supports docker or node12
  main: 'index.js'